### ISSUE TITLE
Explaining the $url == $this->url condition

### ISSUE THREAD

**Issue by ywarnier** [jacwright/RestServer#100]
Hi,

In RestServer.php line 280, you compare `$url` to `$this->url` and, if they not match, you don't return anything.
I don't understand the reason for this comparison. For example, I get `$url = "xapi/statements"` and `$this->url = "https://mydomain.com/xapi/statements"`, so these do not match.

 `$url` comes from the value set by `generateMap()`, which builds the `$url` on the basis of the function documentation, which you suggest (in README.md) to be specifying without the scheme+domain in it.

`$this->url` comes from `$_SERVER['REQUEST_URI']` (in `getPath()`), so it *does* come with the scheme+domain in it.

So this comparison will never be true, as far as I understand...

Any clear idea on how to sort that out?

**Comment by ywarnier** [comment]
I'm replacing it with:
```
                                $urlLength = strlen($url);
                                if ($url == substr($this->url, -$urlLength)) {
```
(it compares $url to the trailing part of $this->url) and that works well, but it goes against the general logic of the comparison as far as I can tell.

**Comment by tyzoid** [comment]
`$_SERVER['REQUEST_URI']` should not include the protocol, see http://php.net/manual/en/reserved.variables.server.php

`getPath()` returns correctly on all systems I've tested; php5.3, php5.5, and php7.1.

What PHP version do you have?

**Comment by ywarnier** [comment]
I'm using Debian Jessie with Apache 2.4 and PHP 5.6 *but* apparently there's something fishy with redirects. I'm trying to locate exactly what's going wrong and I'll be back to you.

**Comment by ywarnier** [comment]
OK, so this was not due to redirections at all but to an HTTP header.
I've added comments to php.net about that here http://php.net/manual/en/context.http.php and here http://php.net/manual/en/language.variables.superglobals.php but it's going to last a bit before it appears.

Basically, when doing something like this:
```
$url = 'https://whatever.com/some-script.php';
$http_options = ['request_fulluri' => true];
$context = stream_context_create(array( 'http' => $http_options));
$fp = fopen($url, 'rb', false, $context);
```

The `request_fulluri` option will change the value of $_SERVER['REQUEST_URI'] and include the scheme and domain in it, so you cannot (in particular for a REST server where HTTP headers are dealt with directly) rely on $_SERVER['REQUEST_URI'] to be strictly the uri without the scheme and domain.

One way to test this would be to test for the beginning of $_SERVER['REQUEST_URI'] being the same as the scheme (for example) as the "://" cannot appear as the URI part after the domain:

```
$scheme = $_SERVER['REQUEST_SCHEME'] . '://';
if (strcmp(substr($_SERVER['REQUEST_URI'], 0, strlen($scheme)), $scheme) === 0) {
    //REQUEST_URI contains the scheme so we need to treat it
}
```
And then in that bit, remove the `$_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['SERVER_NAME']` part (and possibly also the port, if present).
I'd have to think a bit about how to do this best (probably through a preg_replace()), but I guess you're much more comfortable with that @tyzoid (after all, you wrote a REST server lib).

Is that alright or do you see something wrong in my reasoning?

**Comment by tyzoid** [comment]
Probably the easiest thing is to trim this before calling RestServer. Perhaps something like this?

    // Process REQUREST_URI - Reset it to a consistant state.
    $_SERVER['REQUEST_URI'] = preg_replace('/https?:\/\/[^\/]*/', '', $_SERVER['REQUEST_URI'];

**Comment by ywarnier** [comment]
That would leave the $_SERVER['REQUEST_URI'] altered for the rest of the application. Not a good idea (anything could try to use it).

**Comment by tyzoid** [comment]
Right, but the value shouldn't contain the full URL, just the server's URI, which is the path to the requested resource from webroot. Fixing it before calling RestServer also fixes it for other libraries/code that relies on the documented functionality of `REQUEST_URI`

**Comment by ywarnier** [comment]
I cannot agree with you, sorry :-)
$_SERVER should not be altered by any library. It should be treated as read-only. Otherwise the applications cannot trust the PHP language behaviour.
I agree that REQUEST_URI is badly documented, though.

**Comment by tyzoid** [comment]
Let me explain my reasoning a little bit more completely, because I wrote the other comment when I was in a hurry.

As you wrote earlier:
>
>     $url = 'https://whatever.com/some-script.php';
>     $http_options = ['request_fulluri' => true];
>     $context = stream_context_create(array( 'http' => $http_options));
>     $fp = fopen($url, 'rb', false, $context);
> 
> The request_fulluri option will change the value of `$_SERVER['REQUEST_URI']` and include the scheme and domain in it

This means that essentially code that you are calling changes the value of `$_SERVER['REQUEST_URI']` from the expected value of `'/resquest/endpoint.ext?params'` to `'http://example.com/resquest/endpoint.ext?params'`

Since this only occurs due to code that your application is calling, it would seem to me to be the responsibility of your application to reset the value to the expected value (either by using something like the regex I proposed as an example, or by setting it to a temporary value, and resetting after your call), rather than the responsibility of the library to deal with a modification that appears to be out of the standard value for this field.

Furthermore, your comment of
> `$_SERVER` should not be altered by any library. It should be treated as read-only.

only seems to support this opinion. I agree that `$_SERVER` should not be altered. But it shouldn't have been altered by your application in the first place.

I could be convinced otherwise, however this appears to be an issue of unintended side effects of the function you are calling. Certainly if RestServer caused a change in environment variables, I would see it as the responsibility to remove these side effects from RestServer.

**Comment by ywarnier** [comment]
I must agree on that. I was a bit blindsided by the fact that I use another lib for that, but you're right. Nice catch!
I'll try to find a solution with the initial stream_context_create() to avoid it modifying $_SERVER.

I'll close this as your argument completely superseeds mine.

**Comment by tyzoid** [comment]
Glad we could see eye to eye on this. Let me know if you encounter any other issues in RestServer.

**Comment by ywarnier** [comment]
Will do.
