### ISSUE TITLE
Extend the Class with another class

### ISSUE THREAD

**Issue by samuelkaufmann** [jacwright/RestServer#119]
Is it possible to add more functionality via the `extends` in the main API Class controller
`class apiController extends dbController {}`

**Comment by samuelkaufmann** [comment]
mor functionality -sorry for the typo

**Comment by tyzoid** [comment]
Possibly... what are you trying to accomplish by doing so?

**Comment by samuelkaufmann** [comment]
I got a DB-Controller and would like to 'extend' the class with the following Class:
'
<?php
	class Database {
		private static $instance = null;
		private $config;
		private $pdo;
		private function __construct() {
			$this->config = parse_ini_file(__DIR__.'/config/dbconfig.ini');
			$this->pdo = new PDO($this->config['engine'].':host='.$this->config['host'].';dbname='.$this->config['dbname'],	$this->config['user'],$this->config['password']);
		}
		public static function instance() {
			if(Database::$instance == null) {
				Database::$instance = new Database();
			}
			return Database::$instance;
		}
		public function connection() {
			return $this->pdo;
		}
	}
?>

'

**Comment by tyzoid** [comment]
It may work... have you tested it to see? It's not something I've tested myself, but as long as the actual api endpoints are defined in the child class, I think it should work.

Let me know if you get any errors while trying.
