### ISSUE TITLE
nginx 500 status

### ISSUE THREAD

**Issue by Karttin** [jacwright/RestServer#31]
Hi,

I am trying to use RestServer.php in a nginx.

I have changed the htaccess to conf as mentioned in this http://stackoverflow.com/questions/10102616/i-cant-make-restler-work

I am getting a 500 error status

Same code works fine in Apache.

<code>
if (method_exists($obj, 'init')) {
    $obj->init(); //here i am getting 500 error
}
if (!$noAuth && method_exists($obj, 'authorize')) {
    if (!$obj->authorize()) {
        $this->sendData($this->unauthorized(true));
        exit;
    }
}
$result = call_user_func_array(array($obj, $method), $params);
    if ($result !== null) {
        $this->sendData($result);
    }
</code>

Any help appreciated.

Kay

**Comment by jacwright** [comment]
Seems odd since calling init on $obj has nothing to do with nginx. What is getting output in your PHP error logs? You should check there.

**Comment by tyzoid** [comment]
Tagging as obsolete, since there hasn't been a comment in over 2 years. Re-open if this is still a followed issue.
