### ISSUE TITLE
document_root problems 

### ISSUE THREAD

**Issue by mariohr** [jacwright/RestServer#32]
on creating the object, the root path could be different in a linux and windows php server. it comes without slash in the beginning, causing 400 error... fixing in the class creator.

		if ($dir == '.') {
		  $this->root = '/'; 
		}
		else {
			if (substr($dir, -1) != '/') {
				$dir = $dir . '/';
			}	
			if (substr($dir, 1) != '/') {
				$dir = '/' . $dir;
			}	
			$this->root = $dir;
		}

**Comment by hugoman** [comment]
mariohr, you was on nice path, just the last substr is bad

if ($dir == '.') {
  $this->root = '/'; 
}
else {
	if (substr($dir, -1) != '/') {
		$dir = $dir . '/';
	}   
	if (substr($dir, 0, 1) != '/') {
		$dir = '/' . $dir;
	}   
	$this->root = $dir;
}
