### ISSUE TITLE
POST not working

### ISSUE THREAD

**Issue by jibap** [jacwright/RestServer#36]
Hi !

Thanks for your job, very nice !
I have two methods GET who works perfectly, but my POST method not works : 
/**
     * Saves a content 
     *
     * @url POST /files/$filename
     */
    public function saveFile($filename, $data)
    {
        return $data;
    }
The server respond 404 - Not found

If you get it before ?

Thanks

**Comment by jibap** [comment]
OK i found posting you this issue, i used a plugin in my chrome : https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi
for allow CORS, but it crash POST requests !!!

Thank you

**Comment by stravag** [comment]
I have the same issue... I created a controller method to listen on POST requests, but I always receive a 404 response. Any insights? GET methods work fine.

    /**
     * Some comment
     *
     * @url POST /myMethod
     */
    public function myMethod($data) {
        return true;
    }

**Comment by harsh-sparsh** [comment]
May I know where this "urlMap.cache" is located ?
I am not able to find this file on my server.

**Comment by stravag** [comment]
@harsh-sparsh: it's a file created in this directory https://github.com/jacwright/RestServer/tree/master/source/Jacwright/RestServer when using the RestServer.
