### ISSUE TITLE
Composer Package

### ISSUE THREAD

**Issue by karneaud** [jacwright/RestServer#37]
i've used your framework and must admit it is pretty easy and cool for micro-small projects. i'm hoping You/ We can look at packaging it with probably Idiorm & Paris to offer a nice project framework start up.

**Comment by karneaud** [comment]
tried using composer and got this message Your requirements could not be resolved to an installable set of packages.
```
  Problem 1
    - The requested package jacwright/restserver could not be found in any versi
on, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
n problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by karneaud** [comment]
Tried to install using git and composer install and got the following error

````
Composer could not find a composer.json file in C:\Users\ME\git\chubby\vendor\ja
cwright\RestServer
To initialize a project, please create a composer.json file as described in the
https://getcomposer.org/ "Getting Started" section
````

**Comment by stevleibelt** [comment]
Well, two things.
First of all, I made a mistake by using uppercase chracters.
Seconldy, @jacwright simple missed to put it on packagist.org.

@jacwright I can submit it to packagist if you want to (and allow me this to do). I will fix the uppercase issue in another pull request.

Kind regards

**Comment by stevleibelt** [comment]
see pull [request/41](https://github.com/jacwright/RestServer/pull/41)

**Comment by stevleibelt** [comment]
@karneaud thanks for reporting this issue :+1:

**Comment by jacwright** [comment]
@stevleibelt please submit!

**Comment by stevleibelt** [comment]
@karneaud an @jacwright 
damn it, this situation really frustrates me. I've published this repository at packagist (and also fixed the broken links in [pull request 42](https://github.com/jacwright/RestServer/pull/42).
But whenever I call the url, I get back a 500. As you can see, I've published [a lot](https://packagist.org/packages/net_bazzline/) of packages already - so I thought I know what I am doing.

@jacwright Is it possible you gain me write access to this repository? Then I can setup "auto updating" to this repository to packaigst.
I've wrote a mail ti packagist already with the question to gain me some log informations for the 500. Maybe they will answer me soon.
I'm off for a few days, so please be patient.

Kind Regards

stev

**Comment by karneaud** [comment]
Not sure if this was by design but had to use
```
 use \DeathMiner\RestServer\RestServer as Server;
```
could possibly shorten it further by removing the last > RestServer

**Comment by stevleibelt** [comment]
@karneaud as mentioned in issue [45](https://github.com/jacwright/RestServer/issues/45), the "DeathMiner" namespace is not part of this project.

The use statement in your php file should look like the following line:

```php
use \Jacwright\RestServer\RestServer
```

Indeed, we could shorten the name by removing the last "Rest" from the class name.
This would lead to incompatibility across all available and installed packages. I think this is not worth the affort.

Kind Regards

**Comment by karneaud** [comment]
Odd...i guess i am using someone else's package
