### ISSUE TITLE
oauth example

### ISSUE THREAD

**Issue by gauravpadia** [jacwright/RestServer#38]
Hello,

Does anybody have any working example for authentication with oauth ? 

Thanks.

**Comment by designstorming** [comment]
I'm having the same holdup in development. Anyone with solution?

**Comment by designstorming** [comment]
I've found a way (well an idea at least which I'll test today). I'm gonna use [this oauth library](http://ngiriraj.com/socialMedia/oauthlogin/) (you may any other) and store data in session, which will be checked in **authorize** method.
