### ISSUE TITLE
Calling rest without parameters

### ISSUE THREAD

**Issue by fredericks** [jacwright/RestServer#39]
Hi,

I'm using the code below:

    /**
     * Get Charts
     
	 * @url GET /charts
	 * @url GET /charts/$id
	 * @url GET /charts/$id/$date
	 * @url GET /charts/$id/$date/$interval/
	 * @url GET /charts/$id/$date/$interval/$interval_months
     */
    public function getCharts($id=null, $date=null, $interval = 30, $interval_months = 12) {
  		echo "$id, $date, $interval, $interval_months";
                .....

But, when I call (from browser) /charts (without any parameter) I get this result from the echo above:
0, 1, 2, 3

Am I doing something wrong? is this a bug? Does it work this way by design?

Thanks
Federico

**Comment by fredericks** [comment]
didn't anybody have the same behavior?

**Comment by fredericks** [comment]
thanks...it works perfectly now!

**Comment by jacwright** [comment]
Thank you for reporting it.
