### ISSUE TITLE
Rest Response Format

### ISSUE THREAD

**Issue by karneaud** [jacwright/RestServer#43]
How does one change the Response format e.g. return an html response rather than a json response?

**Comment by akasparas** [comment]
@karneaud,
Issues generally should not be used for support requests. But as this topic is not documented, let consider it a request to document format selection. :-)
Format selection is performed in the getFormat() function https://github.com/jacwright/RestServer/blob/master/source/Jacwright/RestServer/RestServer.php#L339-366 . If I follow it correctly then selection options are (in this precedence):
- GET parameter 'format', i.e. http://.../rest.php/controller/action?format=html
- HTTP request's header Accept says JSON is ok
- dot-format syntax, i.e. http://.../rest.php/controller/action.html
- POST parameter 'format' or cookie 'format' if later is configured in your PHP request_order
- contents of $_SERVER['HTTP_FORMAT'] -- have no idea how and where this can come from and what it's doing (possibly bug)
- uses text/plain.

**Comment by karneaud** [comment]
@akasparas ...thanks..where would one get support requests for this? i eventually figured it out but this is a good write up. Glad i was not the only one who say that 'HTTP_FORMAT' thanks!
