### ISSUE TITLE
Using RestServer without ReWrite

### ISSUE THREAD

**Issue by karneaud** [jacwright/RestServer#44]
is there any way we cant use REST without the URLRewrite? 

also can we map GET parameters to paths thus

e.g. 
>  rest/?endpoint=user

can resolve to
```
/**
* @url GET rest/$endpoint/user
*/
```

**Comment by jacwright** [comment]
This is currently not supported. If you would like to add support for it (using a configuration property so that it can be turned on/off) I would be happy to accept it.
