### ISSUE TITLE
Autoloading Classes in composer

### ISSUE THREAD

**Issue by karneaud** [jacwright/RestServer#45]
Not sure if this is by design but I notice that RestServer contains multiple classes in a single file. when installed by composer

I'm encountering a problem where by RestException class can only be instantiated if I instantiate the RestServer class thus while

```
$server = new  \DeathMiner\RestServer\RestServer;
$exception = new \DeathMiner\RestServer\RestException;
```
succeeds

```
$exception = new \DeathMiner\RestServer\RestException;
```
throw an error

> Class DeathMiner\RestServer\RestException not found

please advise as I am new to this composer utility

**Comment by stevleibelt** [comment]
Hi @karneaud 

the problem "multiple classes in one file" is now solved.
You can benefit from composer even more by using the autoloading file he creates.

Just require the "path/to/vendor/autoload.php" in your "index.php" and autoloading should work like a charm.

If there is any trouble with this, simple reopen this issue.

By the way "DeathMiner" is not the namespace of this package. Maybe you did something wrong with your composer file? Composer has a great [FAQ](https://getcomposer.org/doc/).

**Comment by karneaud** [comment]
@stevleibelt 

> By the way "DeathMiner" is not the namespace of this package. Maybe you did something wrong with your composer file? Composer has a great FAQ.

Well it works for me when I looked at the composer autoload file create the namespace was I typed it. Will check it again but this was what I was seeing and experiencing at the time.
