### ISSUE TITLE
PUT variables

### ISSUE THREAD

**Issue by Wikunia** [jacwright/RestServer#48]
How to get the put variables?

This is my `curl` request:
` curl -i -H "Accept: application/json" -X PUT -d description=test http://..../100`

My code:
```
    /**
     * Update a link
     * @url PUT /$id
     */
    public function updateLink($id = null, $data)
    {
        var_dump($data);
    }
```
I thought that the `$data` variable is the requested variables but it doesn't work (returns `NULL`)

**Comment by Wikunia** [comment]
I can use:
`parse_str(file_get_contents("php://input"),$data);`

**Comment by jacwright** [comment]
It should be, at either https://github.com/jacwright/RestServer/blob/master/source/Jacwright/RestServer/RestServer.php#L260 or https://github.com/jacwright/RestServer/blob/master/source/Jacwright/RestServer/RestServer.php#L274
I am not sure why it wouldn't be in your particular situation or setup without debugging.

**Comment by jacwright** [comment]
You might try deleting the `urlMap.cache` file. This is often a source of problems when it isn't updated.
