### ISSUE TITLE
404 when new function is added

### ISSUE THREAD

**Issue by emoran** [jacwright/RestServer#49]
Hi,

I'm having problems adding a new function in my code, the test or main is working good but when I created a new GET function and test it with postman I'm getting 404 error. This is how my function looks like:

```
        /**
         * Get all customers functions
         *
         * @url GET /customers/$id
         */
        public function getCustomers{
            return "customer information working...";
        }
```
It happens also if I use a POST method. There's something additional I need to to or implement?

Thanks in advance,

**Comment by designstorming** [comment]
try adding
```
$server = new Jacwright\RestServer\RestServer('debug');
$server->refreshCache(); // <----- this line here
```

**Comment by emoran** [comment]
Thanks @designstorming still not working, root path is working great, but this new one I can see it exposed.

**Comment by designstorming** [comment]
```
public function getCustomers{
            return "customer information working...";
        }
```
Have you added parentheses?
```
public function getCustomers(){
            return "customer information working...";
        }
```

**Comment by emoran** [comment]
Thanks again @designstorming I just modified my httpd.config adding:


```
<Directory "my_directory_where_my_project_is_hosted">
    AllowOverride All
    Order allow,deny
    allow from all
</Directory>
```

And now is working fine,
