### ISSUE TITLE
Usability on Microsoft IIS

### ISSUE THREAD

**Issue by mdelorimier** [jacwright/RestServer#50]
On IIS on Window there seems to be an issue with the definition of the root path.

I've aded this simple line after line 68 of RestServer.php
```
// Set the root
$dir = dirname(str_replace($_SERVER['DOCUMENT_ROOT'], '', $_SERVER['SCRIPT_FILENAME']));
$dir =  str_replace('\\', '/', $dir);
```

I'm new to github so not sure how to push this.

Great project by the way!

**Comment by jacwright** [comment]
Added in 554f73e4. Thank you!
