### ISSUE TITLE
Content-Type response text/plain;charset=UTF-8 No JSON

### ISSUE THREAD

**Issue by emoran** [jacwright/RestServer#51]
Hi guys, 

I'm running a GET method but in specific returning an object or a simple array is getting text/plain instead JSON here's mi function:

```
  /**
        * Returns a JSON string object with all geolocations with projects and stations
        *
        * @url GET /points/
        */
public function getEstaciones(){ 
      return array("success" => "Logged in ");
}
```

Do I need to set something additional here?

**Comment by jacwright** [comment]
It should be working if `application/json` is in the request's `Accept` header. If you'd like to force json you could use `/points` as your endpoint and `/points.json` in your request.

Perhaps we could add support for a default format if `Accept` has a `*/*` or if the header doesn't exist. Feel free to add and open a pull request.
