### ISSUE TITLE
Error in RestServer.php

### ISSUE THREAD

**Issue by Dormage** [jacwright/RestServer#54]
Created a new Virtual Host, fresh install of RestServer.
Copied the example over to the root folder of the Virtual Host and got the following error.

PHP Parse error:  syntax error, unexpected '[' in /RestServer/source/Jacwright/RestServer/RestServer.php on line 250

Checked the RestServer.php on line 250 and the error makes no sense. 

Any ideas?

**Comment by princeofbubbles** [comment]
I second that. 	$call[2] = []; makes no sense to me or my code hinter either...

**Comment by farooquiyasir** [comment]
'[]' is a notation for array initialization and is supported in PHP 5.4 and above. If your PHP version is less than 5.4, you can simply replace this statement by:-

$call[2] = array();

**Comment by princeofbubbles** [comment]
thanks farooquiyasir! I was suspecting something on those lines :-)
sorry!

**Comment by jacwright** [comment]
Either syntax works. If you'd like to submit a PR for `array();` instead of `[];` I'd be happy to merge it.
