### ISSUE TITLE
Entry point not on the root

### ISSUE THREAD

**Issue by Surfoo** [jacwright/RestServer#62]
Hello,

I'm trying to install RestServer on my dev environment, my entry point is not on the root of the server but in a "api" directory :  `http://dev.com/my_username/api/index.php`

But URLs/Path are different, I added a var_dump() line 254 (between the 2 if) and I had :+1: 

```
string(20) "my_username/api/client"
string(22) "/my_username/api/client"
```

So, it failed for the next condition ($url == $this->url), and I had a 404.

My temporary fix was to comment the following code in `addClass` method : 

```
if (substr($basePath, 0, 1) == '/') {
    $basePath = substr($basePath, 1);
}
```

The / is not removed, and it works like a charm now...

Did I miss something in the config?

Thanks.

**Comment by aligin** [comment]
Agree. This helps.

**Comment by aligin** [comment]
So, after some researches I've realized that the problem is in the request that come from the web server.
If we looked the $path variable from the getPath() method we see this results:
Win+Apache: /api/v1/reports/global/1/1
Linux+nginx+fcgi: api/v1/reports/global/1/1
I suggest to add in the end of the method this getPath()

```
if (substr($path, 0, 1) == '/') {
			$path = substr($path, 1);
		}
```

**Comment by jacwright** [comment]
It sounds like you are not prefixing your URLs with a slash as is intended in the method comments.

It should be:

```php
/**
 * @url POST /login
 */
```

and NOT:

```php
/**
 * @url POST login
 */
```

If you fix this then everything should work as intended.

**Comment by aligin** [comment]
Sorry, but the code is fine.
```
$mode = 'debug'; // 'debug' or 'production'
$server = new \Jacwright\RestServer\RestServer($mode);
$server->addClass('\fmongraph\controllers\ReportController', '/api/v1/reports');
```
Controller
```
class ReportController
{
    private $_zabbixProvider;
    function __construct()
    {
        $this->_zabbixProvider = new \fmongraph\impl\ZabbixProvider();
        $this->_zabbixProvider->Authorize();
    }

    /**
     * Returns a JSON string object to the browser when hitting the root of the domain
     *
     * @url GET /global/$fromDate/$tillDate
     */
    public function GlobalPriorsByDate($fromDate, $tillDate)
```

**Comment by jacwright** [comment]
Thank you for the additional info. I will look into it.

**Comment by jacwright** [comment]
Are you on a Windows machine? It might be a difference between Windows and *nix. If so, could you replace line 70 from
```php
$dir = dirname(str_replace($_SERVER['DOCUMENT_ROOT'], '', $_SERVER['SCRIPT_FILENAME']));
```
to
```php
$dir = str_replace('\\', '/', dirname(str_replace($_SERVER['DOCUMENT_ROOT'], '', $_SERVER['SCRIPT_FILENAME'])));
```
And report whether that fixes the problem?

**Comment by aligin** [comment]
With this change the problem is fixed, thanks.

**Comment by jacwright** [comment]
Thank you for reporting @Surfoo and verifying @aligin! Now works better on Windows.

**Comment by Surfoo** [comment]
I'm a unix server, not windows, and my URL is correct:
`@url POST /login` 

I'll test the fix :-)

**Comment by jacwright** [comment]
The cause of this issue is that `$this->root` should equal `'/'` I believe. If you could `var_dump($this->root)` in the constructor that would help too.

**Comment by aligin** [comment]
Windows:
<pre class='xdebug-var-dump' dir='ltr'>
<small>D:\Server\Sites\fmon.mos.ru\www\graphapi.fmon.mos.ru\vendor\jacwright\restserver\source\Jacwright\RestServer\RestServer.php:80:</small><small>string</small> <font color='#cc0000'>'/'</font> <i>(length=1)</i>
</pre>
Linux (Debian):
```
string(1) "/"
```
