### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by qazimusab** [jacwright/RestServer#64]
I just copied over the example to my server and am getting this error in RestServer.php:

Parse error: syntax error, unexpected '[' in /home/content/46/12363346/html/gomedina/REST/RestServer-master/RestServer-master/source/Jacwright/RestServer/RestServer.php on line 260

**Comment by jacwright** [comment]
This is because you are using an older version of PHP (< 5.4). There is no reason we need to use the newer syntax however. I will make a fix for this.

**Comment by jacwright** [comment]
Fixed in 8cc8ae9 and is in master. Let me know if that worked for you.
