### ISSUE TITLE
handleError not verbose in production

### ISSUE THREAD

**Issue by Surfoo** [jacwright/RestServer#66]
Hello,

Sometimes, datas from the client are bad and I need to send a 400 error with an explicit error message. But in production mode, we don't have messages:
`$message = $this->codes[$statusCode] . ($errorMessage && $this->mode == 'debug' ? ': ' . $errorMessage : '');`

I really need to send error messages in production, maybe only on 4xx errors?

**Comment by jacwright** [comment]
Good call. This was a convenience mechanism that prevents a fully functioning REST API.
