### ISSUE TITLE
Unable to get routing to work for new functions

### ISSUE THREAD

**Issue by riples** [jacwright/RestServer#67]
I have setup my REST Server using your example and can successfully navigate to **\\{SERVER}\RestApi** which brings up `"Hello World!"`.

However, when I navigate to anything else outside of the root, I get `404 Not Found` errors for everything.

I have added a new basic function in my `TestController`:
```
    /**
     * Returns a list of sites
     *
     * @url GET /sites
     */
    public function getSites()
    {
    	return "Site List";
    }
```

My `index.php` file looks like:
```
<?php
    $loader = include __DIR__ . '/vendor/autoload.php';
    
    require __DIR__ . '/vendor/RestServer/RestServer.php';
    require __DIR__ . '/controllers/TestController.php';
    
    spl_autoload_register(); // don't load our classes unless we use them
    
    $mode = 'debug'; // 'debug' or 'production'
    $server = new \Jacwright\RestServer\RestServer('debug');
    // $server->refreshCache(); // uncomment momentarily to clear the cache if classes change in production mode
    
    $server->addClass('TestController');
    
    $server->handle();
?>
```

And my `.htaccess` file looks like so:
```
# Apache needs to let you overrite this (AllowOverride Indexes or AllowOverride All)
DirectoryIndex index.php
<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteCond %{REQUEST_FILENAME} !index\.php$
	RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>
```
Then I am trying to navigate to **\\{SERVER}\RestApi\sites**

However, I cannot work out why it won't successfully redirect.  If I add garbage to the `.htaccess` file I get internal server errors so I know it is reading my `.htaccess` file correctly.

Any ideas where I am going wrong?

Thanks

**Comment by projectramio** [comment]
Did you ever solve this? please post, I am having the same issue :(

**Comment by jacwright** [comment]
I believe this is a bug on a windows box. I am unable to test it out on mac. If you are able to find and fix the issue I will gladly accept a pull request.

**Comment by riples** [comment]
Sorry, yes I did manage to fix this and should have posted my results.  Very sorry about that.
@jacwright - you are correct (well kind of).  The issue I found was that I was running this from a WAMP Server and by default installation, WAMP turns off (or never turns on) the `mod_rewrite` module which is required for the .htaccess file to make the reroutes correctly.

You can turn this on two ways: 1. Left click on the WAMP tray icon, select Apache -> Apache Modules->rewrite_module (probably the easist method).  Or 2. Manually edit the httpd.conf file and uncomment the line `#LoadModule rewrite_module modules/mod_rewrite.so` (take out the # sign).

Also worth mentioning is that I did end up modifying my `.htaccess` file in the following way:
```
# Apache needs to let you overrite this (AllowOverride Indexes or AllowOverride All)
DirectoryIndex index.php
<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteRule ^$ index.php [QSA,L]
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>
```

Hope that helps.

**Comment by riples** [comment]
This issue could probably be closed now I'm guessing.

**Comment by projectramio** [comment]
Thank you :) I am using Linux, so guess there is no httpd.conf file for me??( new to this :) ) edited apache2.conf file so that it says 

> AllowOverride All
insted of 
> AllowOveride None

i think that would be equivalent to what you did with the httpd.conf. or am I wrong? :)
well, I still have the problem. Others have suggested that it is about folder organization. 
i'll post if I find the solution :) please post any suggestions :)

**Comment by projectramio** [comment]
solved it by running 
`sudo a2enmod rewrite`
then restarted the server 
`sudo service apache2 restart`

your answers helped :)
