### ISSUE TITLE
What is the format using DELETE

### ISSUE THREAD

**Issue by gillivt** [jacwright/RestServer#69]
I tried passing the $data variable in through the function and accessing by $data->id, but this gives an error in the Rest Server. The body sent was {"id":"1"}. I also tried just putting $id in the function call and this also gave an error. There is no mention of DELETE in the example code. I am however very impressed with the simplicity of the rest server.

Do I send in the id as raw json in the body or as a url parameter as in GET

**Comment by jacwright** [comment]
A DELETE request shouldn't take a body. It should use a URL like `/projects/$projectId` or `/songs/$songId` etc.
