### ISSUE TITLE
Using querystring parameters in GET request

### ISSUE THREAD

**Issue by kevjett** [jacwright/RestServer#75]
Is there any way to use named querystring parameters in GET requests? I have multiple parameters and would rather have them named than arbitrarily put together with slashes in the url.

I would like to call this method as: www.example.com/search?query=test&country=us&page=1&pageSize=20

It keeps erroring saying Missing argument for all of them.

`

    /**
	* @url GET /search
	*/
	public function search($query, $country, $page, $pageSize) {
		$service = new SearchService();
		$results = $service->search($query, $country, $page, $pageSize);
		return $results;
	}

`

**Comment by jacwright** [comment]
You can access parameters in the query string like you would in any regular PHP application.

```php
/**
* @url GET /search
*/
public function search($query, $country, $page, $pageSize) {
    $service = new SearchService();
    $results = $service->search($_GET['query'], $_GET['country'], $_GET['page'], $_GET['pageSize']);
    return $results;
}
```
