### ISSUE TITLE
unauthorised method is always called with (true)

### ISSUE THREAD

**Issue by joseporto** [jacwright/RestServer#79]
``` php
public function unauthorized($ask = false)
```

but it only get's called via: 

``` php
$this->sendData($this->unauthorized(true)); //@todo unauthorized returns void
```

So this always fires the browser's login dialog, right before my interceptor. I had to change it to `false`, but I'm trying to refrain from tampering with the library itself.

Did you ever considered adding this as a init option. Or, on the Controller's `authorize()` method, we could set this up per controller. For XHR requests, for example, I don't want the web app to fire the login dialog everytime. But I could if the user is on mobile.. just an example.

**Comment by jacwright** [comment]
You can call server->unauthorized() yourself of course. Do you have thoughts on how to allow this to be customizable. If I set it to false, then others who want true will be upset. Ideas on the API to allow this to be set?

**Comment by vchokshi** [comment]
Hi I am running into this same problem. 

In my controller, I have 

```
public function authorize() {
  return authorizeToken(); //Checks a JSON Web Token Authorization: Bearer
}
```

Would this make sense?

```
if (!$noAuth && method_exists($obj, 'authorize')) {
 try {
  $auth = $obj->authorize();
} catch (RestException $e {
 throw $e;
}
```

Or would it be better to catch the fail in authorizeToken() and throw a custom RestException from there?

**Comment by tyzoid** [comment]
Jacwright: Any reasoning against overriding that method in the controller itself?

**Comment by jacwright** [comment]
I don't think so. But to be honest, I don't have time to maintain this project (as you may have noticed). I'm looking for someone who uses it and is interested in taking over maintenance.

**Comment by tyzoid** [comment]
I'd be happy to fulfull that roll, if you're looking to hand it off.

**Comment by joseporto** [comment]
I use it as well, and would be happy to share responsibility. Again, great work.

Regards,

**Comment by tyzoid** [comment]
I'm pushing this back to the 1.2.0 release, when we work on pluggable auth modules.

**Comment by tyzoid** [comment]
I'll write some documentation on implementing the AuthServer interface at some point, but it should be fairly self-explanatory. An example implementation can be found at \Jacwright\RestServer\Auth\HTTPAuthServer, written for backwards compatability.

Let me know if you experience any issues with implementing this.
