### ISSUE TITLE
How can I handle HTTP access control (CORS)

### ISSUE THREAD

**Issue by gcman105** [jacwright/RestServer#85]
Hi, I'm getting **Access-Control-Allow-Origin** errors.

> XMLHttpRequest cannot load http://192.168.0.30/api/customer/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.

How can I set the header to allow for **Access-Control-Allow-Origin**?

**Comment by tyzoid** [comment]
I would recommend you add this header in your server software, i.e. apache or nginx. Both have corrosponding documentation for adding headers to your responses.
