### ISSUE TITLE
RestServer in sub directory doen't work

### ISSUE THREAD

**Issue by turbopixel** [jacwright/RestServer#91]
Our rest api doesn't work anymore. Still got a "error: 404" message. The rest api framework can't find the `@url /notifications/getAll` path with the fix 4024098ed93a4

*\Jacwright\RestServer\RestServer::getPath() - Line 368*

Before `ltrim()`
 * `notifications/getAll`

After `ltrim()`
 * `/notifications/getAll`

The RestServer framework called in a sub directory <domain.tld>/source/rest/notifications/getAll
We received this:
```
{
    "error": {
        "code": 404,
        "message": "Not Found"
    }
}
```

Quick solution in our system that works:

    $server->addClass('Endpoints\Notification', '//notifications');

**Comment by tyzoid** [comment]
Sorry for the mixed info - I made a bug once I replicated the issue. Can you verify the bugfix/#90 fixes this?

**Comment by turbopixel** [comment]
Your commit 0891f7dcf9aacc from #90 fix this bug. Thank you!

**Comment by tyzoid** [comment]
Alright. Thanks for confirming.
